---
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
  order:
    image: ruby
    entrypoint: bash
    command: ['-c', 'cd /app; bundle install; rake db:migrate; padrino s -h  0.0.0.0']
    volumes:
      - ./orders:/app
    links:
      - rabbitmq:rabbitmq
    ports:
      - 3000:3000
  customer:
    image: ruby
    entrypoint: bash
    command: ['-c', 'cd /app; bundle install; ruby app.rb']
    volumes:
      - ./customers:/app
    links:
      - rabbitmq:rabbitmq
  # counter:
  #   build: counter
  #   environment:
  #     RACK_ENV: production
  # sender:
  #   build: rabbitmq-sender
  #   links:
  #     - rabbitmq:rabbitmq
  #     - counter:counter
  # listener:
  #   build: rabbitmq-listener
  #   links:
  #     - rabbitmq:rabbitmq
