---
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "25672:25672"
  sender:
    build: rabbitmq-sender
    links:
      - rabbitmq:rabbitmq
  listener:
    build: rabbitmq-listener
    links:
      - rabbitmq:rabbitmq
