---
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
  order:
    image: ruby
    entrypoint: bash
    command: ['-c', 'cd /app; bundle install; rake db:migrate; padrino s -h  0.0.0.0']
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
    volumes:
      - ./orders:/app
    links:
      - rabbitmq:rabbitmq
    ports:
      - 3000:3000
  customer:
    image: ruby
    entrypoint: bash
    command: ['-c', 'cd /app; bundle install; ruby app.rb']
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
    volumes:
      - ./customers:/app
    links:
      - rabbitmq:rabbitmq
