---
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
  order:
    build: orders
    links:
      - rabbitmq:rabbitmq
    ports:
      - 3000:3000
  # counter:
  #   build: counter
  #   environment:
  #     RACK_ENV: production
  # sender:
  #   build: rabbitmq-sender
  #   links:
  #     - rabbitmq:rabbitmq
  #     - counter:counter
  # listener:
  #   build: rabbitmq-listener
  #   links:
  #     - rabbitmq:rabbitmq
